"""tables

Revision ID: 0f546042a9e8
Revises: 
Create Date: 2022-08-07 12:02:04.992831

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f546042a9e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('addresses_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('line_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('line_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='addresses_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_addresses_line_2', 'addresses', ['line_2'], unique=False)
    op.create_index('ix_addresses_line_1', 'addresses', ['line_1'], unique=False)
    op.create_index('ix_addresses_id', 'addresses', ['id'], unique=False)
    op.create_index('ix_addresses_country', 'addresses', ['country'], unique=False)
    op.create_index('ix_addresses_city', 'addresses', ['city'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('customers_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], name='customers_address_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='customers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_customers_last_name', 'customers', ['last_name'], unique=False)
    op.create_index('ix_customers_id', 'customers', ['id'], unique=False)
    op.create_index('ix_customers_first_name', 'customers', ['first_name'], unique=False)
    op.create_index('ix_customers_email', 'customers', ['email'], unique=False)
    op.create_index('ix_customers_created_at', 'customers', ['created_at'], unique=False)
    op.create_index('ix_customers_address_id', 'customers', ['address_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='orders_customer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='orders_pkey')
    )
    op.create_index('ix_orders_state', 'orders', ['state'], unique=False)
    op.create_index('ix_orders_start_date', 'orders', ['start_date'], unique=False)
    op.create_index('ix_orders_payment_method', 'orders', ['payment_method'], unique=False)
    op.create_index('ix_orders_id', 'orders', ['id'], unique=False)
    op.create_index('ix_orders_customer_id', 'orders', ['customer_id'], unique=False)
    op.create_index('ix_orders_brand', 'orders', ['brand'], unique=False)
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_brand', table_name='orders')
    op.drop_index('ix_orders_customer_id', table_name='orders')
    op.drop_index('ix_orders_id', table_name='orders')
    op.drop_index('ix_orders_payment_method', table_name='orders')
    op.drop_index('ix_orders_start_date', table_name='orders')
    op.drop_index('ix_orders_state', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_customers_address_id', table_name='customers')
    op.drop_index('ix_customers_created_at', table_name='customers')
    op.drop_index('ix_customers_email', table_name='customers')
    op.drop_index('ix_customers_first_name', table_name='customers')
    op.drop_index('ix_customers_id', table_name='customers')
    op.drop_index('ix_customers_last_name', table_name='customers')
    op.drop_table('customers')
    op.drop_index('ix_addresses_city', table_name='addresses')
    op.drop_index('ix_addresses_country', table_name='addresses')
    op.drop_index('ix_addresses_id', table_name='addresses')
    op.drop_index('ix_addresses_line_1', table_name='addresses')
    op.drop_index('ix_addresses_line_2', table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
